--
--  La base de datos tiene tres tablas:
--
--    tbl0                tbl1                tbl2
--    ---------------     ---------------     ---------------
--    K0  CHAR(1)         K0  CHAR(1)         K1  INT
--    c01 INT             K1  INT             c21 FLOAT
--    c02 INT             c12 FLOAT           c22 INT
--    c03 CHAR(4)         c13 INT             c23 DATE
--    c04 FLOAT           c14 DATE            c24 FLOAT
--                        c15 FLOAT           c25 CHAR(5)
--                        c16 CHAR(4)
--
--  Escriba una consulta que retorne las columnas `K0` y `c16` de los
--  registros de la tabla `tbl1` en los que el texto de `c16` empieza con la
--  misma letra de `K0`.
--
--  Resultado esperado:
--
--    K0   c16
--  0  E  EGFD
--  1  B  BDEE
--  2  C  CCCE
--
--  Escriba su consulta debajo de esta línea.
--
